services:
  - type: web
    name: ecommerce-site
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ecommerce-site.onrender.com
      - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: false
  - key: APP_URL
    value: https://ecommerce-site.onrender.com
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: your-db-host.render.com
  - key: DB_PORT
    value: 3306
  - key: DB_DATABASE
    value: your_database_name
  - key: DB_USERNAME
    value: your_username
  - key: DB_PASSWORD
    value: your_password
